INSERT INTO account(name, password) VALUES('test', 'himitu');

INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,0,5,'焼肉');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,0,5, 'ステーキ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,0,5, 'ジビエ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,3,3, 'きのこハンバーグ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,4, 'しゃぶしゃぶ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,4, 'すき焼き');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,4, '煮込みハンバーグ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,5, '親子丼');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,5, 'かつ丼');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,5, '唐揚げ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,5, '牛丼');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,5, '生姜焼き');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,5, 'チキン南蛮');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,5, 'とんかつ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,4,5, '焼き鳥');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,7,5, 'サムギョプサル');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,7,5, 'ジンギスカン');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(1,6,5, 'ハンバーグ');


INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,0,5, 'オイスター');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,1, 'かつおの漬け丼');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,1, 'カレイの煮つけ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,1, '桜えびのかき揚げ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,1, '鯛めし');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,1, 'メバルの煮付け');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,3, 'さんまの塩焼き');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,4, '海鮮鍋');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,5, 'うな重');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,5, '海鮮丼');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,5, '寿司');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,5, '天丼');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,5, '天ぷら');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,4,5, '焼き鮭');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(2,0,5, 'シーフードパスタ');

INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(3,0,4, 'トマト鍋');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(3,4,1, '七草がゆ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(3,4,2, '夏野菜カレー');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(3,4,3, '栗ご飯');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(3,4,3, 'たけのこご飯');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(3,6,4, 'ポトフ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(3,6,5, 'バーニャカウダ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(3,6,5, 'ロールキャベツ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(3,7,5, '薬膳');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(3,0,5, 'ちゃんぽん');

INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,2, '冷や汁');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,3, '炊き込みご飯');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,4, 'おでん');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,5, 'お好み焼き');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,5, 'カレー');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,1,5, 'もつ鍋');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,2, 'そうめん');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,4, '沖縄そば');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,4, '煮込みうどん');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,5, 'うどん');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,5, '塩焼きそば');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,5, '塩ラーメン');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,5, 'そば');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,5, 'つけ麵');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,5, '豚骨ラーメン');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,5, '味噌ラーメン');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(4,0,5, '焼きそば');

INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(5,0,2, '冷やし中華');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(5,0,5, '担々麵');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(5,0,5, 'チャーハン');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(5,0,5, '麻婆豆腐');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(5,1,5, '餃子');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(5,1,5, 'ニラレバ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(5,2,5, 'エビチリ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(5,3,4, '火鍋');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(5,3,5, '回鍋肉');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(5,0,5, 'ラーメン');

INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,2, '冷製パスタ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,4, 'ドリア');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,4, 'シチュー');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,4, 'グラタン');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,5, 'オムライス');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,5, 'カルボナーラ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,5, 'サンドイッチ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,5, 'ナポリタン');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,5, 'ピザ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,5, 'フレンチ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,5, 'ペペロンチーノ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,0,5, 'ミートソーススパゲティ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,1,4, 'ビーフシチュー');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(6,1,5, 'ハンバーガー');


INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'インドカレー');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'ガパオライス');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'キーマカレー');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'サムゲタン');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'スンドゥブ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'タコス');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'チゲ鍋');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'トムヤムクン');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'バインミー');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'パッタイ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'フォー');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, 'ボルシチ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,0,5, '冷麺');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,1,5, 'ケバブ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,1,5, 'シュラスコ');
INSERT INTO eat(categoryid, subcategoryid, seasonid, name) VALUES(7,3,5, 'パエリア');

INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,1,5, 'アンテナショップ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,1,5, 'インテリアショップ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,1,5, '家電量販店');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,1,5, '雑貨屋');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,1,5, '書店巡り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,1,5, 'ショッピングモール');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,1,5, 'デパ地下');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,1,5, '百貨店');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,1,5, '古本屋');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,1,5, 'ホームセンター');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,1,2,5, 'フリーマーケット');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(1,2,1,5, 'アウトレット');

INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, '映画館');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, '演劇鑑賞');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, 'お笑いライブ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, '音楽ライブ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, 'ギャラリー');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, '個展');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, 'デジタルアートミュージアム');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, '図書館');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, '博物館');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, '美術館');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,1,1,5, '漫画喫茶');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(2,2,1,5, 'お城');

INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,1,5, '科学館');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,1,5, 'カラオケ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,1,5, 'ゲームセンター');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,1,5, 'サーカス');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,1,5, '脱出ゲーム');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,1,5, 'テーマパーク');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,1,5, 'ビリヤード');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,1,5, 'ボウリング');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,1,5, 'ボードゲームカフェ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,2,4, '夏祭り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,2,5, 'サバイバルゲーム');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,2,5, 'フェスタ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(3,1,2,5, '遊園地');

INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(4,1,1,5, '屋内スポーツ施設');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(4,1,1,5, 'ジム');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(4,1,1,5, 'スポーツ観戦');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(4,1,1,5, 'バッティングセンター');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(4,1,1,5, 'ボルダリング');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(4,1,2,2, 'プール');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(4,1,2,4, 'スケート');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(4,1,2,5, 'アスレチック');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(4,1,2,5, 'サイクリング');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(4,2,2,2, '海水浴');

INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,2, '風鈴作り体験');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, 'アクセサリー作り体験');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, '織体験');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, 'ガラス工芸体験');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, 'キャンドル作り体験');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, '講演会');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, '座禅体験');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, '食品サンプル作り体験');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, '染色体験');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, '陶芸体験');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, 'ボランティア');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, '料理教室');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,1,5, 'ワークショップ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,1,2,5, '釣り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(5,2,1,5, '工場見学');

INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(6,1,1,5, '犬カフェ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(6,1,1,5, '水族館');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(6,1,1,5, '猫カフェ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(6,1,1,5, 'フクロウカフェ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(6,1,2,5, '動物園');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(6,2,1,5, '乗馬');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(6,2,2,5, '牧場');

INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,1,1,5, '展望台');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,1,2,1, '花見');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,1,2,3, '紅葉狩り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,1,2,5, '大きな公園');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,1,2,5, '植物園');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,1,2,5, 'ハイキング');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,2,1,1, 'いちご狩り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,2,1,2, 'さくらんぼ狩り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,2,1,2, 'もも狩り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,2,1,3, 'ぶどう狩り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,2,1,3, 'りんご狩り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,2,1,4, 'みかん狩り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,2,1,5, '鍾乳洞');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,2,2,2, 'ラフティング');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(7,2,2,5, 'グランピング');

INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(8,1,1,5, '写真を撮る');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(8,1,1,5, '商店街巡り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(8,1,2,5, '寺社仏閣巡り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(8,1,2,5, '日本庭園');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(8,1,2,5, 'パワースポット巡り');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(8,2,1,5, '道の駅');

INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(9,1,1,5, 'スーパー銭湯');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(9,1,1,5, 'マッサージ');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(9,2,1,5, '温泉');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(9,1,1,5, 'プラネタリウム');
INSERT INTO act(categoryid, vehicleid, weatherid, seasonid, name) VALUES(9,1,1,5, 'サウナ');